---
- name: Enumerate active WinRM sessions
  ansible.builtin.include_tasks: enumerate.yml
  tags:
    - winrm_cleanup
    - winrm_cleanup_enumerate

- name: Terminate stale WinRM sessions
  ansible.builtin.include_tasks: terminate.yml
  tags:
    - winrm_cleanup
    - winrm_cleanup_terminate

- name: Deploy scheduled cleanup task
  ansible.builtin.include_tasks: scheduled.yml
  tags:
    - winrm_cleanup
    - winrm_cleanup_scheduled
